project:
  title: "TEC-IN1002B Introduction to Data Science Projects"
  type: website
  output-dir: docs
editor: visual

website:
  title: "IN1001B Introduction to Data Science Projects"
  page-navigation: true
  sidebar:
    contents:
      - href: TEC-IN1002B-index.qmd
        text: Home

author: 
  - name: Alan R. Vazquez
    affiliations:
      - name: Department of Industrial Engineering
        
format:
  html:
    toc: true
    shift-heading-level-by: 1

  revealjs:
    output-ext: "slides.html"
    chalkboard: true
    multiplex: true
    footer: "Tecnologico de Monterrey"
    logo: IN1002b_logo.png
    css: style.css
    slide-number: True
revealjs-plugins:
  - pointer 

