---
title: "Tools for Data Science: Part II"
subtitle: "IN1002B: Introduction to Data Science Projects"
author: 
  - name: Alan R. Vazquez
    affiliations:
      - name: Department of Industrial Engineering
format: 
  revealjs:
    chalkboard: false
    multiplex: true
    footer: "Tecnologico de Monterrey"
    logo: IN1002b_logo.png
    css: style.css
    slide-number: True
    html-math-method: mathjax
editor: visual
jupyter: python3
---

## Agenda

</br>

1.  Data cleaning and wrangling with Python

## Data wrangling

- Data wrangling is the process of transforming raw data into a clean and structured format.

- It involves merging, reshaping, filtering, and organizing data for analysis.

- Here, we illustrate some special functions of the **pandas** for cleaning common issues with a dataset. 

Let's import the **pandas** library in Python

```{python}
#| echo: true

import pandas as pd
```

## Example

Consider an industrial engineer who receives a messy Excel file from a manufacturing client. The data file is called "industrial_dataset.xlsx", which file includes data about machine maintenance logs, production output, and operator comments. 

The **goal** is to clean and prepare this dataset using pandas so it can be analyzed.

Let's read the data set into Python

```{python}
#| echo: true

# Load the Excel file into a pandas DataFrame.
client_data = pd.read_excel("industrial_dataset.xlsx")
```

##

```{python}
#| echo: true

# Preview the dataset.
client_data.head()
```

## Remove duplicate rows

</br></br>

Duplicate or identical rows are rows that have the same entries in every column in the dataset.

If only one row is needed for the analysis, we can remove the duplicates using the `.drop_duplicates()` function.

```{python}
#| echo: true

client_data_single = (client_data
                     .drop_duplicates()
                      )
```

##

The `client_data_single` dataframe does not have duplicate rows.

```{python}
#| echo: true

client_data_single.head()
```

## Add an index column

</br>

In some cases, it is useful to have a unique identifier for each row in the dataset. We can create an identifier using the function `.assign` with some extra syntaxis. 


```{python}
#| echo: true

client_data_single = (client_data_single
                      .reset_index(drop = True)
                      .assign(ID = lambda x: x.index + 1)
                      ) 
```

##

The new column is appended to the end of the dataframe.

```{python}
#| echo: true

client_data_single.head()
```

##

To bring it to the begining of the array, we can use the `.filter()` function.

```{python}
#| echo: true

client_data_single = (client_data_single
.filter(['ID', 'Machine ID',	'Output (units)',	
        'Maintenance Date', 'Operator', 'Comment'])
)
client_data_single.head(3)  
```


## Fill blank cells

In the dataset, there are columns with missing values. If we would like to fill them with specific values or text, we use the `.fillna()` function. In this function, we use the syntaxis `'Variable': 'Replace'`, where the `Variable` is the column in the dataset and `Replace` is the text or number to fill the entry in.

Let's fill in the missing entries of the columns `Operator`, `Maintenance Date`, and `Comment`.

```{python}
#| echo: true

complete_data = (client_data_single
                .fillna({'Operator': 'Unknown', 
                'Maintenance Date': '2023-01-01',
                'Comment': 'None'})
                ) 
```

##

```{python}
#| echo: true

complete_data.head()
```

## Replace values

</br>

There are some cases in which columns have some undesired or unwatned values. Consider the `Output (units)` as an example. 

```{python}
#| echo: true

complete_data['Output (units)'].head()
```

The column has the numbers of units but also text such as "error".

##

</br>

We can replace the "error" in this column by a user-specified value, say, 0. To this end, we use the function `.replace()`. The function has two inputs. The first one is the value to replace and the second one is the replacement value. 

```{python}
#| echo: true

complete_data['Output (units)'] = complete_data['Output (units)'].replace('error', 0)
```

##

</br>

Let's check the new column. 

```{python}
#| echo: true

complete_data['Output (units)']
```

Note that the new column is now numeric.

## Split column into multiple ones

There are some cases in which we want to split a column according to a character. For example, consider the column `Comment` from the dataset.

```{python}
#| echo: true

complete_data['Comment']
```

##

The column has some values such as "Requires part: valve" and "Delay: maintenance\n" that we may want to split into columns.

```{python}
#| echo: false
#| output: true

complete_data['Comment']
```

##

</br>

We can split the values in the column according to the colon ":". 

That is, everything before the colon will be in a column. Everything after the colon will be in another column. To achieve this, we use the function `str.split()`. 

One input of the function is the symbol or character for which we cant to make a split. The other input, `expand = True` tells Python that we want to create new columns.


```{python}
#| echo: true
#| output: false

complete_data['Comment'].str.split(':', expand = True)
```

## 

The result is two columns.

```{python}
#| echo: true
#| output: true

split_column = complete_data['Comment'].str.split(':', expand = True)
split_column.head()
```

## 

</br>

We can assign them to new columns in the dataset using the following code.

```{python}
#| echo: true
#| output: true

augmented_data = (complete_data
                  .assign(First_comment = split_column.filter([0]),
                  Second_comment = split_column.filter([1]))
                  )
```

##

```{python}
#| echo: true
#| output: true

augmented_data.head()
```


## Remove characters

</br>

Something that we notice is that the column `First_Comment` has some extra characters like "\n" that may be useless when working with the data. 

We can remove them using the function `str.strip()`. The input of the function is the character to remove. 

```{python}
#| echo: true

augmented_data['First_comment'] = augmented_data['First_comment'].str.strip("\n")
```

## 

</br>

Let's see the cleaned column.

```{python}
#| echo: true

augmented_data['First_comment']
```

## 

</br>

We can also remove other characters.

```{python}
#| echo: true

augmented_data['First_comment'].str.strip("!")
```


## Transform text case

When working with text columns such as those containing names, it might be possible to have different ways of writing. A common case is when having lower case or upper case names or a combination thereof. 

For example, consider the column `Operator` containing the names of the operators. 

```{python}
#| echo: true

complete_data['Operator'].head()
```

## Remove extra spaces

</br>

To deal with names, we first use the `.str.strip()` to remove leading and trailing characters from strings.

```{python}
#| echo: true

complete_data['Operator'] = complete_data['Operator'].str.strip()
complete_data['Operator']
```


## Change to lowercase letters

</br>

We can turn all names to lowercase using the function `str.lower()`.

```{python}
#| echo: true

complete_data['Operator'].str.lower()
```

## Change to uppercase letters

</br>

We can turn all names to lowercase using the function `str.upper()`.

```{python}
#| echo: true

complete_data['Operator'].str.upper()
```

## Capitalize the first letter

</br>

We can convert all names to title case using the function `str.title()`.

```{python}
#| echo: true

complete_data['Operator'].str.title()
```


